version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      # - 443:443
    restart: always  
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/logs:/var/log/nginx
      - ./https/:/home/blog-feng/server/https/

  redis-server:
    image: redis:latest
    ports:
      - 6479:6379
    restart: always

  app:
    build: ./
    image: node:8.16.2
    volumes:
      - ./:/usr/local/app
    restart: always  
    working_dir: /usr/local/app
    command: "sh -c 'npm install -g pm2@latest  && pm2  start  ./build/config/server/index.js'" 
    depends_on:
      - redis-server
    links:
      - redis-server:rd

      